# Site settings
author: Yingqi Chen
title: 
header-img: img/home-bg.png
email: chanwk18@hotmail.com
copyright_name: Yingqi Chen
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  chanwkkk

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
